### ISSUE TITLE
error:missing 1 required positional argument: 'previous_layer'

### ISSUE THREAD

**Issue by szu-lisili** [jwfromm/Riptide#10]
Hi, this is a nice work.  An error occurred to me when I use train_imagenet.py to train a binary resnet18 model, the command I used:
python train_imagenet.py --model q_resnet18 --experiment 2A1W --gpus 0 --binary --bits 2 --model_dir ~/models

But I get the following error:

Traceback (most recent call last):
  File "scripts/train_imagenet.py", line 196, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "scripts/train_imagenet.py", line 192, in main
    tf.estimator.train_and_evaluate(classifier, train_spec, eval_spec)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run   
    return self.run_local()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 374, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1164, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1194, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1152, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "scripts/train_imagenet.py", line 108, in model_fn
    model = get_model(FLAGS.model)
  File "/root/riptide/riptide/get_models.py", line 37, in get_model
    net = models[name](**kwargs)
  File "/root/riptide/riptide/models/resnet18.py", line 30, in __init__
    self.block1_bn1 = nn.BatchNormalization()
  File "/root/riptide/riptide/binary/binary_layers.py", line 257, in BatchNormalization
    return ShiftNormalization(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'previous_layer'

I use tf2.1 and install the tvm from you rpo, can you guide me what to do next?

**Comment by xvyaward** [comment]
Hi, did you solve the problem?
I am facing the same issue

**Comment by jwfromm** [comment]
Hello, this issue is due to ShiftNormalization not being supported in resnet due to its residual connections. I've fixed the model definitions in this commit: https://github.com/jwfromm/Riptide/commit/00ac5de17fb872746f4e0a351b1c7b904a59ce85. The model and training script should now work correctly.
